name: testapplication
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  animated_button_bar: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  widget_and_text_animator: ^1.1.5
  delayed_display: ^2.0.0
  google_fonts: ^6.2.1
  get: ^4.6.6

flutter:


  uses-material-design: true
  assets:
    - assets/images/

